### ISSUE TITLE
Unable to parse data. java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by chene-vert** [lbilli/Jib.jl#12]
I get this error from IB server after calling `Jib.Requests.reqRealTimeBars(ib, 2, Jib.Contract(;conId=544894145756509053,exchange="SMART") , 5, "TRADES", true)`

```
Error: 2 320 Erreur de lecture de la demande.Message id 2.  Unable to parse data. java.lang.NumberFormatException: For input string:  "544894145756509053" 
``` 

Versions :
**IB gateway :**  
 Build 981.2r, Feb 10, 2021 10:36:16 AM 
 Java Version: 1.8.0_152, OS: Linux (amd64, 5.4.101-1-MANJARO)

**Jib**
[f310f2d2] Jib v0.11.1 `https://github.com/lbilli/Jib.jl#master`

**Comment by lbilli** [comment]
That looks suspiciously a high value for a `conId`. How did it come about?

As IB uses Java `int` to store those values, I'd expect that `conId` <  2e9 or thereabout.

**Comment by chene-vert** [comment]
You are right.
That's a bad conID...sorry about that !

A bad copy/past transfert from another python program... pfff

**Comment by chene-vert** [comment]
thanks for your quick reply !
