### ISSUE TITLE
historicalData

### ISSUE THREAD

**Issue by ionuthristodorescu** [lbilli/Jib.jl#4]
What would be an example use of this API ? Thank you.

**Comment by lbilli** [comment]
Here's a quick example to retrieve EUR historical 5min bars:
```julia
using Jib
ib = Jib.connect(4002, 1);    # Connect on port 4002
d, w = Jib.simple_wrap();
Jib.start_reader(ib, w);

# Define contract
eur = Jib.Contract(symbol="EUR", secType="CASH", exchange="IDEALPRO", currency="USD");

# Send request
Jib.reqHistoricalData(ib, 1234, eur, "20200603 16:00:00 EDT", "2 D", "5 mins", "MIDPOINT", true, 1, false)

# Display result
d[:history]
```
Refer to [IB API documentation](http://interactivebrokers.github.io/tws-api/historical_bars.html#hd_request) for more details and the meaning of the arguments.

The function `historicalData()` is a member of `Wrapper` and is provided by the user. It is implicitly invoked when data are received. The one used in this example is defined [here](https://github.com/lbilli/Jib.jl/blob/ecce955c980e829ba438d908996c5cb01ac529f0/src/wrapper.jl#L192).

**Note.** In this case there's a slight deviation from the official IB API implementations: IB calls `historicalData()` multiple times, row by row (`Bar`), whereas `Jib` calls it only once for the whole table (`DataFrame`).

**Comment by ionuthristodorescu** [comment]
THANK YOU, I appreciate the pointers and the example.

**Comment by Sinansi** [comment]
This example is valuable and informative. I suggest if you could put it on the library home page.

**Comment by lbilli** [comment]
Thanks for the feedback.

**Comment by Sinansi** [comment]
@lbilli Thanks for your time and effort!
