### ISSUE TITLE
EOFError on connect

### ISSUE THREAD

**Issue by cfusting** [lbilli/Jib.jl#43]
I'm having some trouble connecting to the API.

`julia> ib = Jib.connect("172.20.176.1", 7496, 1)`

ERROR: EOFError: read end of file
Stacktrace:
  [1] (::Base.var"#wait_locked#715")(s::Sockets.TCPSocket, buf::IOBuffer, nb::Int64)
    @ Base ./stream.jl:947
  [2] unsafe_read(s::Sockets.TCPSocket, p::Ptr{UInt8}, nb::UInt64)
    @ Base ./stream.jl:955
  [3] unsafe_read
    @ ./io.jl:761 [inlined]
  [4] unsafe_read(s::Sockets.TCPSocket, p::Base.RefValue{UInt32}, n::Int64)
    @ Base ./io.jl:760
  [5] read!
    @ ./io.jl:762 [inlined]
  [6] read
    @ ./io.jl:766 [inlined]
  [7] read_one
    @ ~/.julia/packages/Jib/51eDB/src/client.jl:34 [inlined]
  [8] read_msg(socket::Sockets.TCPSocket)
    @ Jib.Reader ~/.julia/packages/Jib/51eDB/src/reader.jl:11
  [9] connect(host::String, port::Int64, clientId::Int64, connectOptions::String, optionalCapabilities::String)
    @ Jib ~/.julia/packages/Jib/51eDB/src/Jib.jl:54
 [10] connect(host::String, port::Int64, clientId::Int64)
    @ Jib ~/.julia/packages/Jib/51eDB/src/Jib.jl:42
 [11] top-level scope
    @ REPL[3]:1

**Comment by lbilli** [comment]
It looks like you are attempting a connection to TWS/IBGateway from a remote host.
By default TWS/IBGateway accepts only connections from `localhost` and rejects any remote connection.

Under Configuration->API->Settings, make sure that:
- `Enable ActiveX and Socket Clients` is checked
- your host address is listed in the `Trusted IPs` box.

Hope this helps.

**Comment by cfusting** [comment]
Thanks for looking at this, and more importantly putting this API together!

The ip address is in fact WSL2's route to localhost within Windows. Your suggestion made me think that to Trader Workstation the request looked external. I whitelisted the address and the problem was resolved.

**Comment by lbilli** [comment]
Glad it helped.
In this context I think `localhost` just means `127.0.0.1` or the IPv6 equivalent `::1`.
Everything else must be whitelisted.
