### ISSUE TITLE
"Central Standard Time" should also reference "America/Chicago"

### ISSUE THREAD

**Issue by maccam912** [lbilli/Jib.jl#6]
https://github.com/lbilli/Jib.jl/blob/ecce955c980e829ba438d908996c5cb01ac529f0/src/utils.jl#L32

My machine (Windows 10) responds with "Central Standard Time" here.

**Comment by lbilli** [comment]
Would you mind telling what version of TWS/IBGateway you are using and what is the setting in the login screen under "More Options" -> "Time Zone"?
Thanks.
